#!/usr/bin/env bash
# Display information of domain and subdomain

inf_Dom () {
    A=$(dig $2.$1 | awk '/ANSWER SECTION:/{getline;print;}')
    RE=$(echo $A | cut -d' ' -f 4)
    IP=$(echo $A | cut -d' ' -f 5)
    echo "The subdomain $2 is a $RE record and points to $IP"
}
if [ $# -lt 1 ]
then
    echo "Usage: 1-world_wide_web DOMAIN SUBDOMAIN(optional)"
elif [ $# -eq 1 ]
then
    inf_Dom "$1" "www"
    inf_Dom "$1" "lb-01"
    inf_Dom "$1" "web-01"
    inf_Dom "$1" "web-02"
else
    inf_Dom "$1" "$2"
fi
