#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
Redirection="\ \treturn 301 https://www.holbertonschool.com\$request_uri;"
Page_404="\ \treturn 404 \"Ceci n'est pas une page\";"
sed -i "/server_name _;/a$Redirection$Page_404" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx start
