#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
Page_404="\ \terror_page 404 \/404.html;\n location  /404.html {\ninternal;\n}"
sed -i "/server_name _;/a$Page_404" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx start
