#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/_404.html
Page_404="\ \terror_page 404 \/_404.html;\n\tlocation  /_404.html {\n\t\tinternal;\n\t}"
Redirection="\ \trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
Xserv="\n\tadd_header X-Served-By \$hostname;"
sed -i "/server_name _;/a$Redirection$Xserv$Page_404" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx start
