#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd.
#	Your script should only display:
#	username
#	user id
#	Home directory path for the user
file="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f 1,3,6
done < "$file"
