#!/usr/bin/env bash
#Script that displays the time for 12 hours and 59 minutes:
#	display hours from 0 to 12
#	display minutes from 1 to 59
hour=0
while [ $hour -le 12 ]
do
    minut=1
    echo "Hour: $i"
    while [ $minut -le 59 ]
    do
	echo $minut
	((minut++))
    done
    ((hour++))
done
